#!/bin/bash

#
# Patch for LTIB cannot running at ubuntu-10.04 LTS .
# Patch base : base on netronix ltib extract from SDK version 1.3 .
# Author : Gallen Lin
# Date : 2010/05/30
#

WORKDIR=$(pwd)
TOOLDIR=$(dirname $0)

if [ "$1" ];then
	testmode="$1"
else
	testmode="0"	
fi

function docmd {
	if [ "$testmode" = "1" ];then
		echo $@
	else
		$@
	fi
}

patch_result="1"
if [ -f "./ltib" ];then
	echo -n "patch ltib ... "
	docmd patch -p0 < "${TOOLDIR}/ltib-ubuntu-10.04.patch"
	patch_result=$?
	echo " [done]"
else
	echo "Please run this patch in \"ltib\" folder !!"
	exit 1
fi

if [ "$patch_result" = "0" ];then
	echo -n "clear temp files ... "
	docmd sudo rm -fr /tmp/rpm*
	docmd sudo rm -fr /opt/freescale
	echo " [done]"
fi

